### PR TITLE
drs: Add auto-detect between tribes and swgb DRS header types

### PR DESCRIPTION
**Pull request by chrisforbes**
The SWGB header is larger to accomodate a larger copyright string. (What
a reason!!)

There are no other differences in the DRS format.

Signed-off-by: Chris Forbes chrisf@ijw.co.nz

### CODE REVIEW

**Comment by fredreichbier** [comment]
Hi Chris, thanks for the pull request! Unfortunately, it breaks Age Of Empires DRS files for me. I guess that is because genie first tries to parse them as SWGB files, which fails because it gets wrong offset / number_of_tables values (because it reads 20 additional copyright bytes).

Maybe a better mechanism to detect SWGB files would be to manually seek to offset 64, read 4 bytes from the stream and compare them with `swgb`, and only invoke `_parse` if they match. What do you think? Unfortunately I have no copy of SWGB, so I can't test.

**Comment by chrisforbes** [comment]
OK, I see it's not quite safe enough. I'll do what you suggest.

**Comment by phrohdoh** [comment]
I do something similar to this but your approach is better.
I seek to 41 then read a single char. If the result is a 't' then it is SWGB, else AOE.

**Comment by fredreichbier** [comment]
Reading SWGB DRS files now works for me. However, it couldn't find the interface DRS file to read the color palette. It's called `interfac.drs` on my AOE2 installation, but `INTERFAC.DRS` on my SWGB installation, and I'm on a case-sensitive system. So I added a command-line option that can be used to specify the filename.

**Pull request closed without merging**
